# Generated by Django 2.2.13 on 2020-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobP',
        ),
    ]
